Refactor SmartDashboard calls to Shuffleboard
flamingchickens1540/toothless pull request #110
Opened 2022-03-07 16:02 UTC by rutmanz

- Makes preferences persistent
- No more `SmartDashboard.put`s in periodic functions
- Layout automatically transfers to whatever drivestation is connected

2022-03-07 16:52 UTC, natesales requested changes

2022-03-07 16:52 UTC, natesales commented on src/main/java/org/team1540/robot2022/utils/ChickenShuffleboard.java
> +    }
IntelliJ auto format would fix this ;)

2022-03-07 16:52 UTC, natesales commented on src/main/java/org/team1540/robot2022/commands/shooter/ShootSequence.java
> +                    if (ChickenShuffleboard.ShooterTab.Tuning.enableManualSetpoints.getBoolean(false) && !DriverStation.isFMSAttached()) { // Make sure this is never going during a competition
Maybe there should be another shooter profile, `TUNING`, that enables this functionality.

2022-03-07 17:26 UTC, knightss27 commented on src/main/java/org/team1540/robot2022/utils/ChickenShuffleboard.java
> +    }
You wouldn't believe what program I used for my last few commits 😳

2022-03-08 00:32 UTC, natesales approved these changes

2022-03-08 00:33 UTC, merged