Add copilot flywheel spinup buttons
flamingchickens1540/toothless pull request #52
Opened 2022-02-23 06:05 UTC by rutmanz

closes #41

2022-02-23 07:02 UTC, natesales requested changes

2022-02-23 07:02 UTC, natesales commented on src/main/java/org/team1540/robot2022/commands/shooter/Shooter.java
I think this was cleaner before. _IntelliJ auto format winkwink_

2022-02-23 15:36 UTC, rutmanz commented on src/main/java/org/team1540/robot2022/commands/shooter/Shooter.java
_vscode auto format disagrees_ but I'll revert it

2022-02-24 05:30 UTC, natesales approved these changes

2022-02-24 05:31 UTC, merged