Add arm limit detection and arm encoder zeroing
flamingchickens1540/toothless pull request #56
Opened 2022-02-26 05:15 UTC by MeechaPooch

-command for zeroing single arm
-command to zero both arms at once
-removed following the two motors so that zeroing can be induvidual

2022-02-26 05:23 UTC, rutmanz requested changes

2022-02-26 05:23 UTC, rutmanz commented on src/main/java/org/team1540/robot2022/commands/climber/Climber.java
> +            if(this.equals(LEFT)) {
This should probably be a `switch`/`case` block instead of an `if`

2022-02-26 05:23 UTC, rutmanz commented on src/main/java/org/team1540/robot2022/commands/climber/Climber.java
> +    public void setClimberVelocity(ArmSide side, double velocity) {
When would we want to set velocity, wouldn't we just want to do position?

2022-02-26 05:23 UTC, rutmanz commented on src/main/java/org/team1540/robot2022/commands/climber/Climber.java
> +        public TalonFX getMotor(Climber climber) {
Also I'm not sure you need to pass the subsystem into the enum, I think there's a cleaner way of doing it, not completely sure though

2022-02-26 05:23 UTC, rutmanz commented on src/main/java/org/team1540/robot2022/commands/climber/ZeroClimber.java
> +// TODO: maybe make this an inline command in RobotWrapper
Yeah, I don't think this needs to be its own class

2022-02-26 05:23 UTC, rutmanz commented on src/main/java/org/team1540/robot2022/commands/climber/ZeroClimberArm.java
> +            new WaitUntilCommand(()->climber.getArmVoltage(side) > VOLTAGE_THRESHOLD),
This doesn't feel like a reliable way to know if it's fully retracted. There are a lot of circumstances that could lead to going over a voltage threshold

2022-02-26 05:48 UTC, rutmanz commented on src/main/java/org/team1540/robot2022/commands/climber/Climber.java
> +        public TalonFX getMotor(Climber climber) {
See https://stackoverflow.com/questions/14800410/how-to-access-parent-class-member-from-nested-class-in-java

2022-02-26 06:46 UTC, natesales commented on src/main/java/org/team1540/robot2022/commands/climber/Climber.java
> +
Remove blank lines and auto format

2022-02-26 18:19 UTC, MeechaPooch commented on src/main/java/org/team1540/robot2022/commands/climber/Climber.java
> +        public TalonFX getMotor(Climber climber) {
Good idea! I'm not sure if it would work with my code though because ArmSide is a static class. I could make it an instance inner class but then you would have to pass it from a climber instance

2022-03-03 04:46 UTC, natesales commented
Added in 767a9db255ad74024a48f6e0bbfa5e770e9b2ed1

2022-03-03 04:46 UTC, closed without merging