Targeting with PID controllers and basic distance calculations from Limelight data.
flamingchickens1540/toothless pull request #6
Opened 2022-02-05 01:51 UTC by knightss27

👋

2022-02-05 02:32 UTC, knightss27 commented on src/main/java/org/team1540/robot2022/Robot.java
> +        System.out.println("Distance: " + 39.37007874*robotContainer.limelight.getCalculatedDistance());
didn't ask.

2022-02-05 04:49 UTC, natesales requested changes

2022-02-05 04:49 UTC, natesales commented on src/main/java/org/team1540/robot2022/commands/drivetrain/PointToTarget.java
> +    // A little testing says kP=0.7 and kD=0.4 are fairly strong.
Default should be set in SmartDashboard

2022-02-05 04:49 UTC, natesales commented on src/main/java/org/team1540/robot2022/commands/drivetrain/PointToTarget.java
> +                System.out.println("Too high a PID value");
Set a SmartDashboard value instead of logging since this might fill up our log buffers really fast. Something like `pointToTarget/isClamping`

2022-02-05 23:26 UTC, natesales approved these changes

2022-02-06 00:10 UTC, rutmanz approved these changes

2022-02-06 01:33 UTC, merged